import 'package:flutter/material.dart';

import '../../../../core/localization/localization.dart';
import '../../domain/entities/filter_settings_entities.dart';

class FilterEditorMatrixSection extends StatelessWidget {
  const FilterEditorMatrixSection({
    super.key,
    required this.schema,
    required this.adjustments,
    required this.colorMatrix,
    required this.onAdjustmentChanged,
  });

  final FilterSettingsSchemaEntity schema;
  final Map<String, int> adjustments;
  final List<double> colorMatrix;
  final void Function(String key, int value) onAdjustmentChanged;

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final scheme = Theme.of(context).colorScheme;
    final matrixSettings = schema.settings
        .where((s) => s.colorMatrix && !s.clientOnly)
        .toList();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Text(
          l10n.tOr('feFilterSectionSettings', 'Filter settings'),
          style: Theme.of(context).textTheme.titleSmall?.copyWith(
            fontWeight: FontWeight.w700,
          ),
        ),
        const SizedBox(height: 8),
        if (colorMatrix.isNotEmpty) ...[
          Text(
            l10n.tOr(
              'feFilterColorMatrixReadOnly',
              'Auto-generated by the server (read-only)',
            ),
            style: Theme.of(context).textTheme.bodySmall?.copyWith(
              color: scheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 6),
          DecoratedBox(
            decoration: BoxDecoration(
              color: scheme.surfaceContainerHighest,
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: scheme.outlineVariant),
            ),
            child: Padding(
              padding: const EdgeInsets.all(10),
              child: Text(
                colorMatrix.map((v) => v.toStringAsFixed(2)).join(', '),
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                  fontFamily: 'monospace',
                  height: 1.4,
                ),
              ),
            ),
          ),
          const SizedBox(height: 14),
        ],
        if (matrixSettings.isEmpty)
          Text(
            l10n.tOr('feFilterSettingsAllDefault', 'All settings use defaults.'),
            style: Theme.of(context).textTheme.bodySmall?.copyWith(
              color: scheme.onSurfaceVariant,
            ),
          )
        else
          for (final group in schema.groups) ...[
            if (matrixSettings.any((s) => s.group == group.key)) ...[
              Text(
                group.label,
                style: Theme.of(context).textTheme.labelLarge?.copyWith(
                  fontWeight: FontWeight.w700,
                ),
              ),
              if (group.description?.trim().isNotEmpty ?? false) ...[
                const SizedBox(height: 2),
                Text(
                  group.description!,
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                    color: scheme.onSurfaceVariant,
                  ),
                ),
              ],
              const SizedBox(height: 8),
              for (final setting in matrixSettings.where(
                (s) => s.group == group.key,
              ))
                Padding(
                  padding: const EdgeInsets.only(bottom: 8),
                  child: _AdjustmentSlider(
                    definition: setting,
                    value: adjustments[setting.key] ?? setting.defaultValue,
                    onChanged: (value) =>
                        onAdjustmentChanged(setting.key, value),
                  ),
                ),
              const SizedBox(height: 6),
            ],
          ],
      ],
    );
  }
}

class _AdjustmentSlider extends StatelessWidget {
  const _AdjustmentSlider({
    required this.definition,
    required this.value,
    required this.onChanged,
  });

  final FilterSettingDefinitionEntity definition;
  final int value;
  final ValueChanged<int> onChanged;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Row(
          children: [
            Expanded(
              child: Text(
                definition.label,
                style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
            Text(
              '$value',
              style: Theme.of(context).textTheme.labelLarge?.copyWith(
                color: scheme.primary,
                fontWeight: FontWeight.w700,
              ),
            ),
          ],
        ),
        Slider(
          value: value.toDouble(),
          min: definition.min.toDouble(),
          max: definition.max.toDouble(),
          divisions: ((definition.max - definition.min) / definition.step)
              .round()
              .clamp(1, 400),
          label: '$value',
          onChanged: (next) => onChanged(next.round()),
        ),
      ],
    );
  }
}
