// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCvdX0p_MMpkp01EEcCuCCA7ElV2DMUp8',
    appId: '1:550929645796:web:45b1aeaa3919f7567becf1',
    messagingSenderId: '550929645796',
    projectId: 'bomibondapp',
    authDomain: 'bomibondapp.firebaseapp.com',
    storageBucket: 'bomibondapp.firebasestorage.app',
    measurementId: 'G-PC4M5W632G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJq4Q5MlourHSGanK88FpJcOGnd6jkgXs',
    appId: '1:550929645796:android:a57bb9271ed4cb807becf1',
    messagingSenderId: '550929645796',
    projectId: 'bomibondapp',
    storageBucket: 'bomibondapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBht-EZj590AQm9tWWLXMr_8cx7Qlrh4lE',
    appId: '1:550929645796:ios:bc7b5ed8e81c2aa47becf1',
    messagingSenderId: '550929645796',
    projectId: 'bomibondapp',
    storageBucket: 'bomibondapp.firebasestorage.app',
    iosClientId: '550929645796-0bc32pdscquvs4kcl3fv3rfcnlocb7bb.apps.googleusercontent.com',
    iosBundleId: 'com.bimobond.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBht-EZj590AQm9tWWLXMr_8cx7Qlrh4lE',
    appId: '1:550929645796:ios:228cfeafd3dad8ee7becf1',
    messagingSenderId: '550929645796',
    projectId: 'bomibondapp',
    storageBucket: 'bomibondapp.firebasestorage.app',
    iosClientId: '550929645796-8m9es0eksvap8549gkm6hh4hm4c8bg3a.apps.googleusercontent.com',
    iosBundleId: 'com.bimobond.bimoBondDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCvdX0p_MMpkp01EEcCuCCA7ElV2DMUp8',
    appId: '1:550929645796:web:b0dd9d7a951f361a7becf1',
    messagingSenderId: '550929645796',
    projectId: 'bomibondapp',
    authDomain: 'bomibondapp.firebaseapp.com',
    storageBucket: 'bomibondapp.firebasestorage.app',
    measurementId: 'G-SDM85GMWTT',
  );
}
