import 'user_entity.dart';

extension UserEntityFollowCounts on UserEntity {
  UserEntity withFollowCountDeltas({
    int followerDelta = 0,
    int followingDelta = 0,
  }) {
    return UserEntity(
      id: id,
      firebaseUid: firebaseUid,
      username: username,
      fullName: fullName,
      email: email,
      phoneNumber: phoneNumber,
      bio: bio,
      avatarUrl: avatarUrl,
      gender: gender,
      dateOfBirth: dateOfBirth,
      isVerified: isVerified,
      instagramUrl: instagramUrl,
      youtubeUrl: youtubeUrl,
      websiteUrl: websiteUrl,
      tiktokUrl: tiktokUrl,
      twitterUrl: twitterUrl,
      snapchatUrl: snapchatUrl,
      spotifyUrl: spotifyUrl,
      pronouns: pronouns,
      creatorCategory: creatorCategory,
      accountType: accountType,
      verificationBadge: verificationBadge,
      likedVideosVisibility: likedVideosVisibility,
      followersListVisibility: followersListVisibility,
      followingListVisibility: followingListVisibility,
      discoverable: discoverable,
      suggestToContacts: suggestToContacts,
      profileViewHistoryEnabled: profileViewHistoryEnabled,
      showActivityStatus: showActivityStatus,
      restrictedMode: restrictedMode,
      showShopOnProfile: showShopOnProfile,
      allowDuetsDefault: allowDuetsDefault,
      allowStitchDefault: allowStitchDefault,
      allowDownloadsDefault: allowDownloadsDefault,
      allowRepostsDefault: allowRepostsDefault,
      showRepostsOnProfile: showRepostsOnProfile,
      isPrivate: isPrivate,
      isProfileLocked: isProfileLocked,
      allowComments: allowComments,
      allowDirectMsgs: allowDirectMsgs,
      messagePermission: messagePermission,
      canPost: canPost,
      language: language,
      theme: theme,
      country: country,
      region: region,
      city: city,
      followerCount: (followerCount + followerDelta).clamp(0, 0x7fffffff),
      followingCount: (followingCount + followingDelta).clamp(0, 0x7fffffff),
      postCount: postCount,
      totalLikes: totalLikes,
      isBanned: isBanned,
      banReason: banReason,
      bannedUntil: bannedUntil,
      fcmToken: fcmToken,
      createdAt: createdAt,
      updatedAt: updatedAt,
      roles: roles,
      wallet: wallet,
      relationCounts: relationCounts,
      lastLocation: lastLocation,
    );
  }
}
