/// Fields updatable via [UpdateField] without replacing the whole form in the UI.
enum CreatePostField {
  description,
  category,
  categoryId,
  type,
  privacyStatus,
  allowComments,
  allowDuets,
  allowStitch,
  isStory,
  isAd,
  isAuctionable,
  duration,
  videoWidth,
  videoHeight,
  locationId,
  playlistId,
  soundId,
  originalPostId,
  auctionItemName,
  auctionItemImageUrl,
  auctionStartingPriceUsd,
  auctionTargetPriceUsd,
  auctionStartedAt,
  auctionEndedAt,
}
